version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: adserver-postgres-dev
    environment:
      POSTGRES_DB: adserver_dev
      POSTGRES_USER: adserver
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tools/scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adserver -d adserver_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: adserver-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: adserver-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adserver.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # RedisInsight for Redis management
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: adserver-redis-insight-dev
    ports:
      - "8081:8001"
    volumes:
      - redis_insight_data:/db

  # LocalStack for AWS services simulation
  localstack:
    image: localstack/localstack:latest
    container_name: adserver-localstack-dev
    environment:
      SERVICES: s3,cloudformation,iam,lambda,logs
      DEBUG: 1
      # Using /var/lib/localstack to avoid "device busy" errors
      # Note: Free version doesn't persist data anyway
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  redis_insight_data:
  localstack_data: